### ISSUE TITLE
Geofence clarification

### ISSUE THREAD

**Issue by chron0** [bitconnector/ttn_mapper_t-beam#11]
Hi, first of all, thanks a lot for sharing this version of ttn_mapper for the tbeam. I am currently playing around with it and i do see join/accept traffic in the TTN console:

```
08:05:13 Forward join-accept to Application Server
08:05:13 Forward join-accept message
08:05:13 Receive join-accept message
08:05:13 Successfully scheduled join-accept for transmission on Gateway Server
08:05:13 Schedule join-accept for transmission on Gateway Server Rx1 Delay 5
```

however, I see no actual payload data. I didnt change anything regarding geofencing so far, so my question is:

How is geofencing supposed to work, i.e. only send data while within geofence or send data only when out of the fenced area? Would that explain why I dont see any payload data yet?

**Comment by chron0** [comment]
I think in hindsight it's not the geofence at all. After letting it stay outside and running countless of the above loop I brought it back inside and connect serial, it's still only putting out "." only - indicating that the otaa register did not actually work on the end device.
Any ideas?

**Comment by chron0** [comment]
ok, never mind, seems like bad timing - after pulling e451c3041ff2f8c2992591d59fd55e2f969fe498 it seems to work now :)

**Comment by chron0** [comment]
![Screenshot_2022-04-25_15-29-35](https://user-images.githubusercontent.com/3270028/165122206-741b8f75-6710-49dd-a6f4-88661209f1ad.png)

31km max distance for far, really awesome. thx again, love your simple approach and littleWAN, the other lmic libs are soooo bloated.

**Comment by bitconnector** [comment]
Yeah getting the Lora module to recive downlinks was a pain in the ass, because you have to switch the radio configuration for getting the downlink. Somehow the radio glitched sometimes to the right settings, so you could successfully join. Because of that I started implementing the sleep function to preserve the credentials :/

Last week I found out that you have to reload the entire radio configuration in order to work properly :D
