### ISSUE TITLE
Feature: Add GPS sleep

### ISSUE THREAD

**Issue by chron0** [bitconnector/ttn_mapper_t-beam#12]
As this implementation seems to be a great basis for the t-beams, we could look into doing more about power saving while in esp32 deep sleep:

https://github.com/JoepSchyns/Low_power_TTGO_T-beam

And for the GPS specifically:

https://github.com/JoepSchyns/Low_power_TTGO_T-beam/blob/master/low_power/neo6m.cpp

As it is noted, no HW modification seem to be necessary and could perhaps yield more battery runtime of the 18650 cell.

**Comment by bitconnector** [comment]
Thanks for the link ;)

Im Already using the AXP Chip(T-Beam v1.0 and v1.1) to cut the power of the GPS when put to sleep permanently. But maybe I can use the parts to completely shut off the radio parts on the ESP

After using Lora I also put the module to sleep not even listening for downlinks currently

I think to ensure the most battery life you have to keep the wakeing time as low as possible only keep the ESP on as long as it is needed

But powering down the GPS in between sending positions doesnt seem to be a option for me because it takes ages to get a proper GPS fix. Its already the slowest part, because the ESP has to wait up to a second to parse the NMEA sentences from the GPS

Maybe there is a mode for the GPS to calculate the position only after a request over serial
